services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JVM_PERFORMANCE_OPTS: "-Xms512M -Xmx750M"

  cache:
    image: redis:8.0-M02-alpine
    restart: always
    ports:
      - ${REDIS_PORT_MAP}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  postgres:
    image: postgres:17.2-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT_MAP}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_VOLUME_PATH}

volumes:
  cache:
    driver: local
